name: Rust
# 修改分支名称，脚本备用

on:
  push:
    branches: [ "master1" ]
  pull_request:
    branches: [ "master1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd src-tauri 
        cargo build --verbose
    - name: Run tests
      run: |
        cd src-tauri 
        cargo test --verbose
