name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd src-tauri 
        cargo build --verbose
    - name: Run tests
      run: |
        cd src-tauri 
        cargo test --verbose
